export const environment = {
  production: false,
  oauthToken: "Bearer BQDt9dG6PvoXx8OT4yOiNKmUVQZFhTCYLEsQH47razzobdcWaP8CHjNeEzkslvVd7mMvENOKaIUfLjhHVM4trRCROKj3YgOOTxL7cfMakUOD75sV88LIHsQ8_WzT-jlzFkhTtAo8P4iMvaVUUITpbIBWp20Y6nLGDvSma4SBqmJrzyvgKFkAxn6t7rOdaDn9uco"
};